server:
  port: 8001
spring:
  application:
    name: employee-provider
eureka:
  client:
    service-url:
      defaultZone: http://www.ss-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip